"""
Step 0 — probing contexts and FFN activations (Sec. 3.1).

For every language lambda the cross-lingual contrastive probing data consists of
  D^-  unsafe context : jailbreak queries paired with safe refusals
                        (data/train_data/<lang>/final_safe.jsonl)
  D^+  benign context : benign (Alpaca) queries paired with normal responses
                        (data/benign/<lang>.json; the responses are generated by the model)

Phase A  Tokenize every (query, response) pair with the chat template and store
         {"query", "full_input_ids", "response_start_idx"}
                                            ->  <prepared_dir>/<LANG>/{safety,benign}.pt
Phase B  Forward each sequence once, hook the input of
         ``model.model.layers[l].mlp.down_proj`` (the FFN neurons n_l^(i)), average it over
         the response tokens and store one (n_samples, FFN_INTERMEDIATE_DIM) matrix per layer
                                            ->  <acts_dir>/<lang>/{safety,benign}/layer_<l>.pt

The prepared sequences are used by the attribution (Eq. 1) and the activation-propagation
pathways (Eq. 6); the activations by the co-activation pathways (Eq. 3-5) and as benign
means for the mean-value interventions.

Usage
  python pathway/extract_ffn_activations.py --languages EN ZH ... \
      --train-data-dir data/train_data --benign-dir data/benign \
      --prepared-dir $OUT_ROOT/prepared_data --activations-dir $OUT_ROOT/ffn_activations
"""

import argparse
import json
import os
import sys
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
from tqdm import tqdm

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lingualpath.config import DEVICE, FFN_INTERMEDIATE_DIM, LANG_TO_TRAINDIR, MODEL_NAME, NUM_LAYERS


# ---------------------------------------------------------------------------
# Probing data
# ---------------------------------------------------------------------------
def load_unsafe_pairs(train_data_dir: str, lang: str) -> List[Tuple[str, str]]:
    """D^-: (jailbreak query, safe refusal) pairs."""
    sub = LANG_TO_TRAINDIR.get(lang.upper(), lang.lower())
    pairs = []
    with open(os.path.join(train_data_dir, sub, "final_safe.jsonl"), encoding="utf-8") as f:
        for line in f:
            if line.strip():
                d = json.loads(line)
                x, y = d.get("instruction", "").strip(), d.get("response", "").strip()
                if x and y:
                    pairs.append((x, y))
    return pairs


def load_benign_queries(benign_dir: str, lang: str, n: Optional[int] = None) -> List[str]:
    """D^+: benign queries in the same language."""
    with open(os.path.join(benign_dir, f"{lang.lower()}.json"), encoding="utf-8") as f:
        queries = [q for q in json.load(f) if isinstance(q, str) and q.strip()]
    return queries[:n] if n else queries


# ---------------------------------------------------------------------------
# Phase A: tokenized (query, response) sequences
# ---------------------------------------------------------------------------
def prompt_ids(tokenizer, query: str) -> torch.Tensor:
    text = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                         tokenize=False, add_generation_prompt=True)
    return tokenizer.encode(text, add_special_tokens=False, return_tensors="pt")[0]


def prepare_pairs(tokenizer, pairs: List[Tuple[str, str]], max_length: int) -> List[Dict]:
    """Teacher-forced sequences: chat prompt followed by the given response."""
    prepared = []
    for x, y in pairs:
        p = prompt_ids(tokenizer, x)
        r = tokenizer.encode(y, add_special_tokens=False, return_tensors="pt")[0]
        full = torch.cat([p, r])[:max_length]
        prepared.append({"query": x, "full_input_ids": full, "response_start_idx": p.shape[0]})
    return prepared


@torch.no_grad()
def prepare_generated(model, tokenizer, queries: List[str], max_new_tokens: int) -> List[Dict]:
    """Sequences whose response is generated greedily by the model."""
    device = next(model.parameters()).device
    prepared = []
    for x in tqdm(queries, desc="  generating"):
        p = prompt_ids(tokenizer, x).unsqueeze(0).to(device)
        out = model.generate(p, max_new_tokens=max_new_tokens, do_sample=False,
                             temperature=None, top_p=None, pad_token_id=tokenizer.eos_token_id)
        prepared.append({"query": x, "full_input_ids": out[0].cpu(), "response_start_idx": p.shape[1]})
    return prepared


def save_prepared(prepared: List[Dict], prepared_dir: str, lang: str, data_type: str) -> None:
    path = os.path.join(prepared_dir, lang, f"{data_type}.pt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    torch.save(prepared, path)
    lens = np.array([p["full_input_ids"].shape[0] - p["response_start_idx"] for p in prepared])
    print(f"  saved {len(prepared)} {data_type} sequences -> {path} "
          f"(response tokens: mean {lens.mean():.0f}, max {lens.max()})")


# ---------------------------------------------------------------------------
# Phase B: response-mean-pooled FFN activations
# ---------------------------------------------------------------------------
@torch.no_grad()
def extract_activations(model, prepared: List[Dict]) -> Dict[int, torch.Tensor]:
    device = next(model.parameters()).device
    acts: Dict[int, torch.Tensor] = {}
    hooks = []
    for l in range(NUM_LAYERS):
        def hook(module, inp, out, l=l):
            acts[l] = inp[0].detach()
        hooks.append(model.model.layers[l].mlp.down_proj.register_forward_hook(hook))

    per_layer: Dict[int, list] = {l: [] for l in range(NUM_LAYERS)}
    for item in tqdm(prepared, desc="  extracting"):
        ids, start = item["full_input_ids"], item["response_start_idx"]
        if start >= ids.shape[0]:                     # empty response
            for l in range(NUM_LAYERS):
                per_layer[l].append(torch.zeros(FFN_INTERMEDIATE_DIM))
            continue
        acts.clear()
        model(input_ids=ids.unsqueeze(0).to(device))
        for l in range(NUM_LAYERS):
            per_layer[l].append(acts[l][0, start:, :].mean(dim=0).float().cpu())
    for h in hooks:
        h.remove()
    return {l: torch.stack(v) for l, v in per_layer.items()}


def save_activations(acts: Dict[int, torch.Tensor], acts_dir: str, lang: str, data_type: str) -> None:
    out = os.path.join(acts_dir, lang.lower(), data_type)
    os.makedirs(out, exist_ok=True)
    for l, t in acts.items():
        torch.save(t, os.path.join(out, f"layer_{l}.pt"))
    print(f"  saved activations -> {out}/")


def main():
    ap = argparse.ArgumentParser(description="Probing contexts D^-, D^+ and FFN activations")
    ap.add_argument("--languages", nargs="+", required=True)
    ap.add_argument("--train-data-dir", required=True, help="dir with <lang>/final_safe.jsonl (D^-)")
    ap.add_argument("--benign-dir", required=True, help="dir with <lang>.json benign queries (D^+)")
    ap.add_argument("--prepared-dir", required=True)
    ap.add_argument("--activations-dir", required=True)
    ap.add_argument("--n-benign", type=int, default=1000, help="number of benign queries per language")
    ap.add_argument("--max-new-tokens", type=int, default=128, help="length of the benign responses")
    ap.add_argument("--max-length", type=int, default=1024, help="maximum sequence length")
    ap.add_argument("--dtype", choices=["float16", "bfloat16", "float32"], default="float16")
    args = ap.parse_args()

    from transformers import AutoModelForCausalLM, AutoTokenizer

    print(f"Loading model {MODEL_NAME} ...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, dtype=getattr(torch, args.dtype),
                                                 device_map=DEVICE)
    model.eval()

    for lang in args.languages:
        print(f"\n[{lang}]")
        safety = prepare_pairs(tokenizer, load_unsafe_pairs(args.train_data_dir, lang), args.max_length)
        save_prepared(safety, args.prepared_dir, lang, "safety")
        benign = prepare_generated(model, tokenizer,
                                   load_benign_queries(args.benign_dir, lang, args.n_benign),
                                   args.max_new_tokens)
        save_prepared(benign, args.prepared_dir, lang, "benign")
        for data_type, prepared in (("safety", safety), ("benign", benign)):
            save_activations(extract_activations(model, prepared), args.activations_dir, lang, data_type)


if __name__ == "__main__":
    main()
